package com.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "EmployeeServerInterfaceDelegate", targetNamespace = "http://server.com/")
public interface EmployeeServerInterfaceDelegate {

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getRoles", targetNamespace = "http://server.com/", className = "com.client.GetRoles")
	@ResponseWrapper(localName = "getRolesResponse", targetNamespace = "http://server.com/", className = "com.client.GetRolesResponse")
	public String getRoles();

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getEmployee", targetNamespace = "http://server.com/", className = "com.client.GetEmployee")
	@ResponseWrapper(localName = "getEmployeeResponse", targetNamespace = "http://server.com/", className = "com.client.GetEmployeeResponse")
	public String getEmployee(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getEmpfromrole", targetNamespace = "http://server.com/", className = "com.client.GetEmpfromrole")
	@ResponseWrapper(localName = "getEmpfromroleResponse", targetNamespace = "http://server.com/", className = "com.client.GetEmpfromroleResponse")
	public String getEmpfromrole(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

}
